### ISSUE TITLE
Change `.trickfilm` files to `.ron`

### ISSUE THREAD

**Issue by DraftedDev** [KirmesBude/bevy_trickfilm#21]
I appreciate the whole `.trickfilm` file format.
But as far as I understand it, it's just RON Syntax with another file ending, thus making the `.trickfilm` file ending just a decoration.
And since most editors (+ editor settings) don't recognize `.trickfilm` files as RON files, I recommend you to change the whole Trickfilm File thing to simply RON.

Thanks for any help.

**Comment by KirmesBude** [comment]
That is probably a good idea since editing the ron directly is the only way right now to create a trickfilm file and should always remain an option.
I will have to look into what that looks like in the Assetloader. I assume it should be able to infer the right AssetLoader based on the target rust type. Worst case I we have <filename>.trickfilm.ron or something like that.
Thanks for the feedback
