### ISSUE TITLE
just_finished can be missed

### ISSUE THREAD

**Issue by KirmesBude** [KirmesBude/bevy_trickfilm#28]
The schedule is not fixed in multi threaded scenarios for a given execution of the problem - at runtime order of systems can change each frame (given no overlapping access, ...).
Since we run in Update and the user is likely running in Update as well, just_pressed can be missed. bevy_input seems to use PreUpdate and presumably (need to check) stages are some kind of har sync points across threads.

One solution: Move stuff into PostUpdate. Or do we just tell users to schedule their systems after our set?

**Comment by PraxTube** [comment]
I was also thinking about moving the Animation Schedule into PostUpdate. The only problem I see with this is that any logic the user would want to perform _after_ trickfilm updates must be run in PostUpdate. Though I don't see why this would be such a huge issue, the Animation Set should run before other Bevy specific system sets anyways (not sure which ones, but it might make sense to run before stuff like TransformPropagation and the likes, which doesn't have much to do with animations but if the user wanted to update transforms based on animations then it would still be possible). I don't know when the graphics get updated but I am guessing at the very very last stage so it's probably not much of an issue.

I personally didn't need to run anything _after_ trickfilm yet, just something that came to my mind. I do find myself often in need to run stuff _before_ it though, in those cases it would be nice if it were in PostUpdate because then it's guaranteed to be run before it.
